### ISSUE TITLE
Clear chunk crashes my game. please help

### ISSUE THREAD

**Issue by SDRStuff** [DrunkShulker/Bartender#33]
Clear chunk crashes my game. please help

**Comment by DrunkShulker** [comment]
Clear chunk uses Baritone. I think ur Baritone broken because u have installed incompatible mods, or installed mods thats are not Forge mods. To fix this, u must create a fresh minecraft instance(=completely new `.minecraft` directory). I highly recommend MultiMC for that. Im closing this issue, next time provide more information..
